on: push

env:
  NODE_VERSION: 18.16.0

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check source code formatting
        run: npx prettier --check .
      - name: Lint source code
        run: npx eslint --max-warnings=0 .
      - name: Run jest
        run: npm run test
